### PR TITLE
More uniform style, spelling fixes, shorter intro.

### PR DESCRIPTION
**Pull request by JesseAlderliesten**
Rewording more uniform (The most important package(s) -> among the most-important packages), removed redundant wording (complete tooldbox / framework -> toolbox / framwork) and fixing various spelling and grammar mistakes. Also dropped the introductory sentence on many packages being not on CRAN.

### CODE REVIEW

**Comment by tuxette** [comment]
@JesseAlderliesten : Thank you for your very careful review of the TV! I reviewed your changes and will accept the pull request as is. I might discuss the removal of the sentence you propose not to include in the introduction with Julie: maybe we will bring it back or at least keep some of its message in a new version.

**Comment by JesseAlderliesten** [comment]
@tuxette : you're welcome. You all thanks for compiling such a useful overview.
I have one additional question: can I delete my forked 'Omics' repository (i.e., https://github.com/JesseAlderliesten/Omics) now, or should I keep it? (are there (CRAN?) guidelines / etiquettes on that)?

**Comment by tuxette** [comment]
I think you can delete it. @zeileis can you confirm?

**Comment by zeileis** [comment]
👍

**Pull request merged**
